2022-02-04 19:52:29,235 ERROR: Exception on /index [GET] [in /Users/leroy/.pyenv/versions/3.9.6/lib/python3.9/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/Users/leroy/.pyenv/versions/3.9.6/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/leroy/.pyenv/versions/3.9.6/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/leroy/.pyenv/versions/3.9.6/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/leroy/.pyenv/versions/3.9.6/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/leroy/.pyenv/versions/3.9.6/lib/python3.9/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/leroy/Dropbox/Works/Dev/Flask/flask-mega-tutorial/microblog/app/routes.py", line 32, in index
    return render_template('index.html', title='Home', form=form, posts=posts)
  File "/Users/leroy/.pyenv/versions/3.9.6/lib/python3.9/site-packages/flask/templating.py", line 148, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/leroy/.pyenv/versions/3.9.6/lib/python3.9/site-packages/jinja2/environment.py", line 1068, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/leroy/.pyenv/versions/3.9.6/lib/python3.9/site-packages/jinja2/environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "/Users/leroy/.pyenv/versions/3.9.6/lib/python3.9/site-packages/jinja2/environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/Users/leroy/.pyenv/versions/3.9.6/lib/python3.9/site-packages/jinja2/loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/Users/leroy/.pyenv/versions/3.9.6/lib/python3.9/site-packages/flask/templating.py", line 59, in get_source
    return self._get_source_fast(environment, template)
  File "/Users/leroy/.pyenv/versions/3.9.6/lib/python3.9/site-packages/flask/templating.py", line 95, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
2022-02-04 19:52:55,400 INFO: Microblog startup [in /Users/leroy/Dropbox/Works/Dev/Flask/flask-mega-tutorial/microblog/app/__init__.py:43]
2022-02-04 19:53:00,627 ERROR: Exception on / [GET] [in /Users/leroy/.pyenv/versions/3.9.6/lib/python3.9/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/Users/leroy/.pyenv/versions/3.9.6/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/leroy/.pyenv/versions/3.9.6/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/leroy/.pyenv/versions/3.9.6/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/leroy/.pyenv/versions/3.9.6/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/leroy/.pyenv/versions/3.9.6/lib/python3.9/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/leroy/Dropbox/Works/Dev/Flask/flask-mega-tutorial/microblog/app/routes.py", line 32, in index
    return render_template('index.jinja', title='Home', form=form, posts=posts)
  File "/Users/leroy/.pyenv/versions/3.9.6/lib/python3.9/site-packages/flask/templating.py", line 148, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/leroy/.pyenv/versions/3.9.6/lib/python3.9/site-packages/jinja2/environment.py", line 1068, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/leroy/.pyenv/versions/3.9.6/lib/python3.9/site-packages/jinja2/environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "/Users/leroy/.pyenv/versions/3.9.6/lib/python3.9/site-packages/jinja2/environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/Users/leroy/.pyenv/versions/3.9.6/lib/python3.9/site-packages/jinja2/loaders.py", line 137, in load
    code = environment.compile(source, name, filename)
  File "/Users/leroy/.pyenv/versions/3.9.6/lib/python3.9/site-packages/jinja2/environment.py", line 757, in compile
    self.handle_exception(source=source_hint)
  File "/Users/leroy/.pyenv/versions/3.9.6/lib/python3.9/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/leroy/Dropbox/Works/Dev/Flask/flask-mega-tutorial/microblog/app/templates/index.jinja", line 6, in template
    {% if form }
jinja2.exceptions.TemplateSyntaxError: unexpected '}'
2022-02-04 19:53:01,367 ERROR: Exception on /index [GET] [in /Users/leroy/.pyenv/versions/3.9.6/lib/python3.9/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/Users/leroy/.pyenv/versions/3.9.6/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/leroy/.pyenv/versions/3.9.6/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/leroy/.pyenv/versions/3.9.6/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/leroy/.pyenv/versions/3.9.6/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/leroy/.pyenv/versions/3.9.6/lib/python3.9/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/leroy/Dropbox/Works/Dev/Flask/flask-mega-tutorial/microblog/app/routes.py", line 32, in index
    return render_template('index.jinja', title='Home', form=form, posts=posts)
  File "/Users/leroy/.pyenv/versions/3.9.6/lib/python3.9/site-packages/flask/templating.py", line 148, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/leroy/.pyenv/versions/3.9.6/lib/python3.9/site-packages/jinja2/environment.py", line 1068, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/leroy/.pyenv/versions/3.9.6/lib/python3.9/site-packages/jinja2/environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "/Users/leroy/.pyenv/versions/3.9.6/lib/python3.9/site-packages/jinja2/environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/Users/leroy/.pyenv/versions/3.9.6/lib/python3.9/site-packages/jinja2/loaders.py", line 137, in load
    code = environment.compile(source, name, filename)
  File "/Users/leroy/.pyenv/versions/3.9.6/lib/python3.9/site-packages/jinja2/environment.py", line 757, in compile
    self.handle_exception(source=source_hint)
  File "/Users/leroy/.pyenv/versions/3.9.6/lib/python3.9/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/leroy/Dropbox/Works/Dev/Flask/flask-mega-tutorial/microblog/app/templates/index.jinja", line 6, in template
    {% if form }
jinja2.exceptions.TemplateSyntaxError: unexpected '}'
