2022-02-04 19:53:02,246 ERROR: Exception on /index [GET] [in /Users/leroy/.pyenv/versions/3.9.6/lib/python3.9/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/Users/leroy/.pyenv/versions/3.9.6/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/leroy/.pyenv/versions/3.9.6/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/leroy/.pyenv/versions/3.9.6/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/leroy/.pyenv/versions/3.9.6/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/leroy/.pyenv/versions/3.9.6/lib/python3.9/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/leroy/Dropbox/Works/Dev/Flask/flask-mega-tutorial/microblog/app/routes.py", line 32, in index
    return render_template('index.jinja', title='Home', form=form, posts=posts)
  File "/Users/leroy/.pyenv/versions/3.9.6/lib/python3.9/site-packages/flask/templating.py", line 148, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/leroy/.pyenv/versions/3.9.6/lib/python3.9/site-packages/jinja2/environment.py", line 1068, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/leroy/.pyenv/versions/3.9.6/lib/python3.9/site-packages/jinja2/environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "/Users/leroy/.pyenv/versions/3.9.6/lib/python3.9/site-packages/jinja2/environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/Users/leroy/.pyenv/versions/3.9.6/lib/python3.9/site-packages/jinja2/loaders.py", line 137, in load
    code = environment.compile(source, name, filename)
  File "/Users/leroy/.pyenv/versions/3.9.6/lib/python3.9/site-packages/jinja2/environment.py", line 757, in compile
    self.handle_exception(source=source_hint)
  File "/Users/leroy/.pyenv/versions/3.9.6/lib/python3.9/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/leroy/Dropbox/Works/Dev/Flask/flask-mega-tutorial/microblog/app/templates/index.jinja", line 6, in template
    {% if form }
jinja2.exceptions.TemplateSyntaxError: unexpected '}'
2022-02-04 19:53:48,706 INFO: Microblog startup [in /Users/leroy/Dropbox/Works/Dev/Flask/flask-mega-tutorial/microblog/app/__init__.py:43]
2022-02-04 19:53:55,036 ERROR: Exception on /exlore [GET] [in /Users/leroy/.pyenv/versions/3.9.6/lib/python3.9/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/Users/leroy/.pyenv/versions/3.9.6/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/leroy/.pyenv/versions/3.9.6/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/leroy/.pyenv/versions/3.9.6/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/leroy/.pyenv/versions/3.9.6/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/leroy/.pyenv/versions/3.9.6/lib/python3.9/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/leroy/Dropbox/Works/Dev/Flask/flask-mega-tutorial/microblog/app/routes.py", line 39, in explore
    return render_template('Index.html', title='Explore', posts=posts)
  File "/Users/leroy/.pyenv/versions/3.9.6/lib/python3.9/site-packages/flask/templating.py", line 148, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/leroy/.pyenv/versions/3.9.6/lib/python3.9/site-packages/jinja2/environment.py", line 1068, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/leroy/.pyenv/versions/3.9.6/lib/python3.9/site-packages/jinja2/environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "/Users/leroy/.pyenv/versions/3.9.6/lib/python3.9/site-packages/jinja2/environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/Users/leroy/.pyenv/versions/3.9.6/lib/python3.9/site-packages/jinja2/loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/Users/leroy/.pyenv/versions/3.9.6/lib/python3.9/site-packages/flask/templating.py", line 59, in get_source
    return self._get_source_fast(environment, template)
  File "/Users/leroy/.pyenv/versions/3.9.6/lib/python3.9/site-packages/flask/templating.py", line 95, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: Index.html
2022-02-04 19:58:10,308 INFO: Microblog startup [in /Users/leroy/Dropbox/Works/Dev/Flask/flask-mega-tutorial/microblog/app/__init__.py:43]
2022-02-04 20:00:40,297 INFO: Microblog startup [in /Users/leroy/Dropbox/Works/Dev/Flask/flask-mega-tutorial/microblog/app/__init__.py:43]
2022-02-04 22:00:25,607 INFO: Microblog startup [in /Users/leroy/Dropbox/Works/Dev/Flask/flask-mega-tutorial/microblog/app/__init__.py:43]
2022-02-04 22:01:55,693 ERROR: Exception on /page=2 [GET] [in /Users/leroy/.pyenv/versions/3.9.6/lib/python3.9/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/Users/leroy/.pyenv/versions/3.9.6/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/leroy/.pyenv/versions/3.9.6/lib/python3.9/site-packages/flask/app.py", line 1492, in dispatch_request
    self.raise_routing_exception(req)
  File "/Users/leroy/.pyenv/versions/3.9.6/lib/python3.9/site-packages/flask/app.py", line 1474, in raise_routing_exception
    raise request.routing_exception  # type: ignore
  File "/Users/leroy/.pyenv/versions/3.9.6/lib/python3.9/site-packages/flask/ctx.py", line 367, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/Users/leroy/.pyenv/versions/3.9.6/lib/python3.9/site-packages/werkzeug/routing.py", line 2041, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/leroy/.pyenv/versions/3.9.6/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/leroy/.pyenv/versions/3.9.6/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/leroy/.pyenv/versions/3.9.6/lib/python3.9/site-packages/flask/app.py", line 1386, in handle_user_exception
    return self.handle_http_exception(e)
  File "/Users/leroy/.pyenv/versions/3.9.6/lib/python3.9/site-packages/flask/app.py", line 1326, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/Users/leroy/Dropbox/Works/Dev/Flask/flask-mega-tutorial/microblog/app/errors.py", line 6, in not_found_error
    return render_template('404.html'), 404
  File "/Users/leroy/.pyenv/versions/3.9.6/lib/python3.9/site-packages/flask/templating.py", line 148, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/leroy/.pyenv/versions/3.9.6/lib/python3.9/site-packages/jinja2/environment.py", line 1068, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/leroy/.pyenv/versions/3.9.6/lib/python3.9/site-packages/jinja2/environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "/Users/leroy/.pyenv/versions/3.9.6/lib/python3.9/site-packages/jinja2/environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/Users/leroy/.pyenv/versions/3.9.6/lib/python3.9/site-packages/jinja2/loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/Users/leroy/.pyenv/versions/3.9.6/lib/python3.9/site-packages/flask/templating.py", line 59, in get_source
    return self._get_source_fast(environment, template)
  File "/Users/leroy/.pyenv/versions/3.9.6/lib/python3.9/site-packages/flask/templating.py", line 95, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: 404.html
